### ISSUE TITLE
ShinnyApp is realoding forever

### ISSUE THREAD

**Issue by ibombonato** [chainofflowers/MyRDatasetExplorer#1]
I am trying to review your App on coursera, but its reloading infinitly 

https://chainofflowers.shinyapps.io/MyRDatasetExplorer/

Please, take a look and fix it as soon as possible.

Cheers

**Comment by chainofflowers** [comment]
Hi! Thank you very much for your care.
I have checked and the app works fine: on which page are you experiencing that issue? Is the page background grey?
If it is just grey, it is not reloading: it's just that sometimes there are few resources available to the free accounts and it gets slower.
If, instead, you mean that the page reloads itself, then I don't know... are you using some particular browser add-ons which might cause this behaviour, like some anonymizer removing the browser agent identification string?
I have used the standard shiny style, the page shouldn't do anything strange, but maybe it's trying to understand if you are using a desktop or a smartphone and fails. I have seen similar behaviours in web apps but I can't say it's the same issue here.
Could you tell me which browser and which OS you're using?

Please let me know, we might have to report this.
Thanks!

Am 25. Mai 2015 22:46:21 MESZ, schrieb Icaro Bombonato notifications@github.com:

> I am trying to review your App on coursera, but its reloading infinitly
> 
> https://chainofflowers.shinyapps.io/MyRDatasetExplorer/
> 
> Please, take a look and fix it as soon as possible.
> 
> Cheers
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chainofflowers/MyRDatasetExplorer/issues/1

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ibombonato** [comment]
After reading the forum, I found that others are experience similar things in other apps. The problem is that the "please wait" loading page keeps reloading the page ever an ever...

After i saw the messages, I try it in another computer, at home, and it works normally. Now, I just tried it again on the same computer that does not work yesterday, and now it is working.

So it was probably a problem with shinny apps server.
